# Generated by Django 4.2.4 on 2023-10-02 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no-name', max_length=256)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('parent_circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.circle')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no-name', max_length=256)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ManyToManyField(blank=True, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('production', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Server',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Empty Message', max_length=2000)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_conversation_type', models.CharField(default='normal', max_length=16)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.circle')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.AddField(
            model_name='circle',
            name='parent_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.server'),
        ),
    ]
