# Generated by Django 4.2.4 on 2023-09-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.circle'),
        ),
        migrations.AddField(
            model_name='server',
            name='production',
            field=models.BooleanField(default=1),
        ),
    ]
