# Generated by Django 4.0.6 on 2023-08-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfo',
            options={'verbose_name_plural': 'Server Info'},
        ),
    ]
