# Generated by Django 4.2.4 on 2023-10-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_last_login'),
        ('main', '0002_circle_creator_alter_circle_parent_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_creator', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circle_creator', to='authentication.user'),
        ),
    ]
