# Generated by Django 4.2.4 on 2023-09-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_circle_server_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='parent_circle',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='parent_server',
        ),
    ]
