# Generated by Django 4.2.4 on 2023-08-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_circle_name_circle_parent_circle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='no-name', max_length=256),
        ),
        migrations.AddField(
            model_name='conversation',
            name='parent_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.circle'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='parent_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.server'),
        ),
    ]
