# Generated by Django 4.2.4 on 2023-09-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message_current_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circle',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
