# Generated by Django 4.2.4 on 2023-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_whitelistedemails_options'),
        ('main', '0004_conversation_date_time_created_conversation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='authentication.user'),
        ),
    ]
