# Generated by Django 4.2.4 on 2023-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_whitelistedemails_options'),
        ('main', '0005_conversation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(blank=True, to='authentication.user'),
        ),
    ]
