# Generated by Django 4.0.6 on 2023-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_serverinfo_options'),
        ('main', '0007_message_conversation_message_date_time_created_and_more'),
    ]

    operations = [
    ]
