# Generated by Django 4.0.6 on 2023-09-07 16:30

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Whitelisted Emails',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('online', models.BooleanField(default=0)),
                ('date_created', models.DateField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, to='authentication.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='main.circle'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='main.server'),
        ),
    ]
