# Generated by Django 4.2.4 on 2023-08-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_whitelistedemails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistedemails',
            options={'verbose_name_plural': 'Whitelisted Emails'},
        ),
    ]
