# Generated by Django 4.2.4 on 2023-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_whitelistedemails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(to='authentication.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
