# Generated by Django 4.2.4 on 2023-08-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_conversation_message_date_time_created_and_more'),
        ('authentication', '0005_user_followers_user_x_user_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.circle'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.server'),
        ),
    ]
