# Generated by Django 4.2.4 on 2023-10-24 15:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
