# Generated by Django 4.2.4 on 2023-10-24 15:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_primary_color_user_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
