# Generated by Django 4.2.6 on 2023-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_primary_color_alter_user_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(default={}),
        ),
    ]
