# Generated by Django 4.2.6 on 2023-11-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_logins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logins',
        ),
        migrations.AddField(
            model_name='user',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
