# Generated by Django 4.2.6 on 2023-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_user_logins_user_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
