# Generated by Django 4.2.6 on 2023-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.JSONField(blank=True, default={'notifications': []}),
        ),
    ]
